services:
  order-management-service:
    baseUrl: 'http://localhost:8082'
    clientName: 'order-management-service'
    connectionTimeout: 1000
    readTimeout: 150
    cache:
      name: 'order-management-service'
      enabled: false
      expireAfter: PT1S
      size: 1
  hermes:
    baseUrl: 'http://localhost:8082'
    clientName: 'hermes'
    connectionTimeout: 1000
    readTimeout: 500
