spring:
  application:
    name: sandboxAPP

services:
  order-management-service:
    baseUrl: 'http://localhost:8082'
    clientName: 'order-management-service'
    connectionTimeout: 10000
    readTimeout: 1500
    cache:
      name: 'order-management-service'
      enabled: false
      expireAfter: PT1S
      size: 1
  hermes:
    baseUrl: 'http://localhost:8082'
    clientName: 'hermes'
    connectionTimeout: 10000
    readTimeout: 1500

management:
  endpoints:
    web:
      exposure:
        include: "*"
