spring:
  application:
    name: sandboxAPP

services:
  order-management-service:
    baseUrl: 'http://localhost:8082'
    clientName: 'order-management-service'
    connectionTimeout: 10000
    readTimeout: 1500
    cache:
      name: 'order-management-service'
      enabled: true
      expireAfter: PT10S
      size: 10
  hermes:
    baseUrl: 'http://localhost:8082'
    clientName: 'hermes'
    connectionTimeout: 10000
    readTimeout: 1500

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.client.requests: true
        http.server.requests: true
      percentiles:
        http.client.requests: 0.5, 0.90, 0.95, 0.99
        http.server.requests: 0.5, 0.90, 0.95, 0.99
      slo:
        http.client.requests: 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 30s
